services:
  mlflow-postgres:
    image: postgres:13-alpine
    container_name: mlflow_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_MLFLOW_USER}
      - POSTGRES_PASSWORD=${POSTGRES_MLFLOW_PASSWORD}
      - POSTGRES_DB=${POSTGRES_MLFLOW_DB}
    volumes:
      - mlflow-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_MLFLOW_USER}"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - mlflow-network
  
  minio:
    image: minio/minio
    container_name: mlflow_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - mlflow-network
  
  create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 10
      mc alias set local http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
      mc ls local/mlflow-artifacts || mc mb local/mlflow-artifacts;
      mc policy set public local/mlflow-artifacts;
      exit 0;
      "
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    restart: "no"
    networks:
      - mlflow-network

  mlflow-server:
    build:
      context: ./mlflow
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      mlflow-postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      create-bucket:
        condition: service_completed_successfully
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri postgresql://${POSTGRES_MLFLOW_USER}:${POSTGRES_MLFLOW_PASSWORD}@mlflow-postgres:5432/${POSTGRES_MLFLOW_DB} 
      --default-artifact-root s3://mlflow-artifacts/
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - mlflow-network

  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow-server:5000}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL:-http://minio:9000}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - POSTGRES_MLFLOW_HOST=${POSTGRES_MLFLOW_HOST:-mlflow-postgres}
      - POSTGRES_MLFLOW_USER=${POSTGRES_MLFLOW_USER}
      - POSTGRES_MLFLOW_PASSWORD=${POSTGRES_MLFLOW_PASSWORD}
      - POSTGRES_MLFLOW_DB=${POSTGRES_MLFLOW_DB}
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    expose:
      - "8000"
    depends_on:
      - mlflow-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - mlflow-network
    command: uvicorn app:app --host=0.0.0.0 --port=8000
  
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - mlflow-network

volumes:
  mlflow-postgres-data:
  minio-data:

networks:
  mlflow-network:
    driver: bridge