{
 "title": "FastAPI Observability Dashboard",
 "description": "Comprehensive FastAPI dashboard with key performance metrics, request statistics, and system resource monitoring",
 "tags": [
  "fastapi",
  "monitoring",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(http_requests_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"$app_name\", handler!~\"/metrics|none\"})",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Requests Count by Endpoint",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, handler) (http_requests_total{job=\"$app_name\", handler!~\"/metrics|none\"})",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"$app_name\", handler!~\"/metrics|none\"}[5m]) / (rate(http_request_duration_seconds_count{job=\"$app_name\", handler!~\"/metrics|none\"}[5m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$app_name\", handler!=\"/metrics\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoint (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(http_requests_total{job=\"$app_name\", handler!=\"/metrics\"}[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$app_name\"}",
     "legendFormat": "Memory Use"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$app_name\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$app_name\"}[5m])*100",
     "legendFormat": "CPU Use"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$app_name\"}[5m])*100",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}