FROM apache/airflow:2.7.3-python3.9

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /opt/airflow/logs/scheduler /opt/airflow/dags /opt/airflow/plugins \
    && chown -R airflow:airflow /opt/airflow \
    && chmod -R 775 /opt/airflow

USER airflow
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt